# Thank You for downloading tweakin :)
# Each module can be configured separately
# changes can be reloaded with /tweakin reload command [Permission: tweakin.command.reload]
# Some common options are:

# enabled: true # weather or not module should be enabled
# black-list-worlds: [world] # list of worlds where module will not function

# Read the text above each module for more info that module like commands and permissions(if any)
# if you found any issue/bug, join me up on discord: https://discord.gg/tTHs4jKu6f


# its bstats
metrics: true

# list of sections that will be ignored while looking to update this config
# Only use this if your specific config section changes are cleared after reload
# Example: adding rotation-wrench.item to list will ignore that section completely while updating this config
ignored-sections: []

# Right clicking an armor item in an inventory will swap it for whatever armor you're currently holding.
# Permission: tweakin.armorclick
armor-right-click:
  enabled: true

# Right Clicking shulker box in air will show its contents
# Permission: tweakin.shulkerboxclick
right-click-shulker-box:
  enabled: true  

# Create nether portals with any shape,size and with any blocks, remember this only applies to nether portals
# Permission: tweakin.customportal.use
custom-portal:
  enabled: true
  black-list-worlds: []
  # max radius of portal
  radius: 20
  # list of blocks as valid portal frame
  valid-portal-blocks:
    - OBSIDIAN
    - CRYING_OBSIDIAN

# Note Blocks with heads attached to their side will emit the respective mob's sound instead of a note.
# The mob sound's pitch is based on the note block pitch.
# only vanilla mob heads will work
noteblock-mob-sounds:
  enabled: true
  black-list-worlds: []
  # list of heads which will be ignored
  # DRAGON_WALL_HEAD,ZOMBIE_WALL_HEAD,WITHER_SKELETON_WALL_SKULL,SKELETON_WALL_SKULL
  black-list-heads: []

# REQUIRES: ProtocolLib 
# Reacharound Placing allows you to place blocks behind the block you're looking at.
# This can be done either vertically or horizontally, 
# provided you wouldn't be placing a block given normal rules.
# Permissions:
  # tweakin.reacharound.*: grants all permissions given below for reacharound
  # tweakin.reacharound.vertical: permission to place vertically
  # tweakin.reacharound.horizontal: permission to place horizontally
  # tweakin.reacharound.highlight: permission to show highlight
reach-around:
  enabled: true
  black-list-worlds: []
  # list of materials that cant be placed with reacharound
  # use ^NAME to allow a list of blocks that end with NAME, eg. ^SHULKER_BOX 
  black-list-materials:
  - ^SHULKER_BOX
  # weather or not to show future position of block as transperent highlight
  show-highlight: true
  # what should be the color of highlight
  # use 0,16,0 if on 1.17, as blockhighlight is bugged in this 1.17 and colors dont match up
  color: 204,204,204
  # transparency of highlight
  transparency: 50

# Leaves decay much faster when no logs are nearby, or when the leaves are not player placed  
fast-leaf-decay:
  enabled: true
  black-list-worlds: []
  # maximum duration leaves will stay (in seconds)
  duration: 10

# Ladders are slightly tweaked to improve your laddering experience:
  # Right clicking a ladder with another one will place it, allowing you to drop ladders down without risking falling to your death.
  # Shift+right clicking any end of ladder will allow you to reach the another end, resulting in quick climb
# Permission: tweakin.betterladder.* tweakin.betterladder.dropdown, tweakin.betterladder.quickclimb
better-ladder:
  enabled: true
  black-list-worlds: []

# Lapis placed in enchanting table will stay there
lapis-in-table:
  enabled: true 
  black-list-worlds: []

# All recipes will be unlocked when player joins server
# Permission: tweakin.autorecipeunlock
auto-recipe-unlock:
  enabled: true

# Helps to sync nether portals between overworld and nether
# right clicking a nether portal block while holding compass will display the calculated coordinates in compass
# these coordinates will direct where the other portal should be created in the opposite dimension.
# Permission: tweakin.netherportalcoords
nether-portal-coords:
  enabled: true
  # pairs of valid overworld|nether
  world-pairs:
    world: world_nether

# Does what it says, allows player to attack mobs through grass or any other passable block
# Permission: tweakin.swingthroughgrass
swing-through-grass:
  enabled: true

# displays coordinate hud,direction and ingame time at actionbar
# Permission: 
  # tweakin.coordinatehud: permission to use /togglerhud command
  # tweakin.coordniatehud.compassbypass: players having this permission do not require compass to be in inventory (have-compass option should be enabled)
# Command: /togglehud,/thud
coordinate-hud:
  enabled: true
  # weather or not to enable hud when player first joins the server
  enable-on-first-join: true
  # if set to true the hud will only display if player has a compass in there inventory
  have-compass: false
  # intervals in ticks at which hud will update
  interval-ticks: 2 

# Feeding a baby animal a Poisonous Potato has a chance to poison it for a few seconds.
# A baby animal that has been poisoned by this method will never grow into an adult.
# Permission: tweakin.posionpotato.use
poison-potato-usage:
  enabled: true
  black-list-worlds: []
  # chance at which the baby will be poisoned bettween (0-1)
  chance: 0.1
  # list of animals that will not be affected by this
  black-list-animals: []


# The tip of a vine can now be burnt with a Flint and Steel.
# When you do so, the vine will no longer be able to grow.
# Permission: tweakin.burnvinetip.use
burn-vine-tip:
  enabled: true
  black-list-worlds: []

# silence mobs using a name tag
# Permission: tweakin.silencemobs.*, tweakin.silencemobs.silence, tweakin.silencemobs.unsilence
silence-mobs:
  enabled: true
  black-list-worlds: []
  # list of mobs that will not be affected by this tweak
  black-list-mobs:
    - WITHER
    - ENDER_DRAGON
  # weather or not to consume tag after silencing the mob
  consume-tag: false
  # weather or not to actually rename mob after right clicking with name tag
  rename-mob: false
  # list of valid names that can be used on name tag to silence the mob (case sensetive)
  silence-names:
    - "Silence me"
    - "silence me"
    - "Silence plz"
    - "Silence"
    - "silence"
  # list of valid names that can be used on name tag to unsilence the mob (case sensetive)
  unsilence-names:
    - "Unsilence"
    - "unsilence"
    - "Unmute me"
    - "unmute me"

# Adds a wrench which allows to rotate any rotatable block listed in rotatable-materials.
# Permission: tweakin.rotationwrench.use
rotation-wrench:
  enabled: true
  # weather or not item is craftable, if set to false recipes regarding this item will not register
  craftable: true
  # list of valid rotatable blocks
  # use ^NAME to allow a list of blocks that end with NAME, eg. ^_STAIRS  
  rotatable-materials:
    - ^_PISTON
    - OBSERVER
    - DISPENSER
    - ^_STAIRS
    - ^_TERRACOTTA
    - COMPARATOR
    - REPEATER
    - CHEST
    - ^_LOG
  # configuration for item 
  # use ignored-sections option above if the changes get reset after reload
  item:
    id: STICK
    display: "&aRotation Wrench"
    lore:
      - "&6Right click a block to rotate"
    options.model: 100

# Using a Glass Bottle at the cloud levels (126-132 by default) will get you a Bottled Cloud.
# The Bottled Cloud can be right clicked to produce a block floating in midair in front of you.
# The cloud block disappears after a few seconds, but you can right click it with any other block to replace the two.
# The cloud will go back in the bottle when you do this.
# Permission: 
  # tweakin.bottledcloud.*: provides all permissions related to this tweak
  # tweakin.bottledcloud.pickup: provides permission to pickup cloud with glass bottle at given heights
  # tweakin.bottledcloud.use: provides permission to use the bottled cloud
bottled-cloud:
  enabled: true
  black-list-worlds: []
  # minimium height for glass bottle to pickup cloud
  minimum-height: 126
  # maximum height for glass bottle to pickup cloud
  maximum-height: 132
  # configuration of item
  item:
    id: GLASS_BOTTLE
    display: "Bottled Cloud"
    lore:
      - "&7Right-Click in air to place cloud"
    options.model: 101

# A Trowel tool can be crafted with Iron and Sticks.
# The Trowel, when right clicked, will place a random block from your hotbar, making it useful for ruins or paths.
# Permission: 
  # tweakin.trowel.use: provides permission to use the trowel
trowel:
  enabled: true
  # weather or not item is craftable, if set to false recipes(from recipes.yml) regarding this item will not register 
  craftable: true
  # weather or not item should take damage on use, only use for damagable items like iron_hoe
  # Note: max uses of the item depends on what base material you are using example iron_hoe has 250 max durability meaning trowel will have 250 max uses
  take-damage: true
  # configuration for item
  item:
    id: IRON_HOE
    display: "&7Trowel"
    flags:
      - HIDE_ATTRIBUTES
    options.model: 102
    lore:
      - "&7Right-Click to place random blocks from hotbar"


  
